# 主题样式 0跟随系统 1白天 2黑夜
theme: 0

# 像素比 越高越清晰 但是会减缓渲染速度
deviceScaleFactor: 3

# 页面加载状态 'load'|'domcontentloaded'|'networkidle0'|'networkidle2'
# load: 页面完全加载
# domcontentloaded: DOMContentLoaded 事件触发 如果纯静态可以使用
# networkidle0: 500ms内没有网络连接
# networkidle2: 500ms内网络连接数小于2
waitUntil: networkidle2
